### ISSUE TITLE
OPCUA Broken after 2024.10.0

### ISSUE THREAD

**Issue by crumets** [minix1234/hacore_opcua#12]
Hello,

I hope you can you help me with this!
After updating to 2024.10.0 no more data is coming from the opc server and the error is

Logger: custom_components.opcua
Quelle: custom_components/opcua/__init__.py:311
Integration: Opcua
Erstmals aufgetreten: 18:08:34 (52 Vorkommnisse)
Zuletzt protokolliert: 18:08:58

ns=4;s=|var|CODESYS Control for Raspberry Pi MC SL.Wohnraumlueftung.PLC_PRG.Fern, Read Value Error: 'NoneType' object has no attribute 'send_request'
ns=4;s=|var|CODESYS Control for Raspberry Pi MC SL.Wohnraumlueftung.PLC_PRG.OW4[0], Read Value Error: 'NoneType' object has no attribute 'send_request'
ns=4;s=|var|CODESYS Control for Raspberry Pi MC SL.Wohnraumlueftung.PLC_PRG.OW4[1], Read Value Error: 'NoneType' object has no attribute 'send_request'
ns=4;s=|var|CODESYS Control for Raspberry Pi MC SL.Wohnraumlueftung.PLC_PRG.OW4[2], Read Value Error: 'NoneType' object has no attribute 'send_request'

**Comment by JanHre** [comment]
Try 
Opcua: close and after that connect again

**Comment by crumets** [comment]
Did but no change. Here are some more error messages related to it.

Logger: homeassistant.util.package
Quelle: util/package.py:150
Erstmals aufgetreten: 19:47:17 (3 Vorkommnisse)
Zuletzt protokolliert: 19:47:19

Unable to install package opcua==0.98.12: × No solution found when resolving dependencies: ╰─▶ Because there is no version of enum34==1000000000.0.0 and opcua==0.98.12 depends on enum34==1000000000.0.0, we can conclude that opcua==0.98.12 cannot be used. And because you require opcua==0.98.12, we can conclude that your requirements are unsatisfiable.





Logger: homeassistant.config
Quelle: config.py:1300
Erstmals aufgetreten: 19:47:19 (1 Vorkommnisse)
Zuletzt protokolliert: 19:47:19

Platform error: sensor - Requirements for opcua not found: ['opcua==0.98.12'].




Logger: homeassistant.setup
Quelle: setup.py:269
Erstmals aufgetreten: 19:47:19 (1 Vorkommnisse)
Zuletzt protokolliert: 19:47:19

Setup failed for custom integration 'opcua': Requirements for opcua not found: ['opcua==0.98.12'].

**Comment by JanHre** [comment]
Hi Ok
In manifest.json change to this
{
    "domain": "opcua",
    "name": "Opcua",
    "documentation": "https://www.home-assistant.io/integrations/opcua",
    "requirements": ["opcua==0.98.13"],
    "codeowners": ["@minix1234"],
    "version": "0.1.1"
  }

**Comment by crumets** [comment]
Perfect! Thank you!
